# Server config file
server:
  address: localhost
  port: 8080
  read_timeout: 5s
  write_timeout: 5s
  shutdown_timeout: 30s
  idle_timeout: 60s
  access_control_allow_headers: "Content-Type"
  access_control_allow_methods: "GET, POST, PUT, DELETE, OPTIONS"
  access_control_allow_credentials: true

cookie:
  session_name: "session_id"
  session_length: 32
  http_only: true
  secure: false
  # SameSiteDefaultMode = 1
  # SameSiteLaxMode = 2
  # SameSiteStrictMode = 3
  # SameSiteNoneMode = 4
  same_site: 3
  path: "/"
  expiration_age: -1
